### GET request to example server
GET http://localhost:8888/api/auth/login
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJneXVyY2kwOCIsImV4cCI6MTczNDUxNjgxOSwiaWF0IjoxNzM0NTEzMjE5fQ.hhUXoSPQz4h3K5Dhm3Pw-tKvOP1l2LmKrAQ1GMkU-Mo
