server:
  port: 8888

spring:
  application:
    name: tester-fullstack

  datasource:
    url: jdbc:postgresql://localhost:5432/pizzeria
    username: pizzeria
    password: 12345678
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

cors:
  allowed-origins: "http://localhost:4200"
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  max-age: 3600

  logging:
    level:
      org:
        springframework:
          jdbc:
            core: debug
      hu:
        jandzsogyorgy: debug
      root: info
